### PR TITLE
ui change on: pricing, quality and story page. new UI: friendsOf tunga

### PR DESCRIPTION
**Pull request by Wamosrich**
## PR Type
What kind of change does this PR introduce?
- Made Changes on Pricing Page, Quality and Story Page
- Added Friends of Tunga Page and Rules

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number(s): N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by davidsemakula** [comment]
@Wamosrich can u push all the images for ur latest changes a few a missing and breaking the build
screen shot 2018-04-04 at 10 25 55

**Comment by Wamosrich** [comment]
@davidsemakula Images have been added.

**Comment by davidsemakula** [comment]
@Wamosrich can u edit the pull request and point it to the develop branch?
Also do this for all future pull requests.

**Comment by davidsemakula** [comment]
@Wamosrich kill all inline styles and also remove the express.js endpoint added for sending email
I'll share an email endpoint when I resolve the issue with Bart

@bartleijssenaar if there's an email that needs to be sent let's create the template in Mailchimp or Django and share the endpoint with Amos

**Comment by bartleijssenaar** [comment]
@davidsemakula do you mean the email that gets sent from this form:

screen shot 2018-04-04 at 14 37 14

?

**Comment by Wamosrich** [comment]
Ok

**Comment by Wamosrich** [comment]
@davidsemakula The images appear zoomed when added to site, kindly look into it and advise

**Pull request merged**
